# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('mata_kuliah', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('jenis', models.CharField(choices=[('IND', 'Individu'), ('KLM', 'Kelompok')], default='IND', max_length=3)),
                ('status', models.CharField(choices=[('BLM', 'Belum Dikerjakan'), ('SDH', 'Sudah Dikerjakan')], default='BLM', max_length=3)),
                ('deadline', models.DateField()),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
